import os
TEAM_NAME = os.environ["TEAM_NAME"]
SQLALCHEMY_DATABASE_URI = os.environ["SQLALCHEMY_DATABASE_URI"]
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ["SQLALCHEMY_TRACK_MODIFICATIONS"]
SECRET_KEY = os.environ["SECRET_KEY"]